[package]
name = "rayexec_debug"
version.workspace = true
edition.workspace = true

[dependencies]
rayexec_proto = { path = '../rayexec_proto' }
rayexec_execution = { path = '../rayexec_execution' }
rayexec_error = { path = '../rayexec_error' }
rayexec_io = { path = '../rayexec_io' }
futures = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
regex = { workspace = true }
url = { workspace = true }
bytes = { workspace = true }
scc = { workspace = true }
