[package]
name = "rayexec_execution"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
rayexec_error = { path = "../rayexec_error" }
rayexec_parser = { path = "../rayexec_parser" }

ahash = { workspace = true }
arrow = { workspace = true }
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-cast = { workspace = true }
arrow-ipc = { workspace = true }
arrow-ord = { workspace = true }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
hashbrown = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
parquet = { workspace = true }
rayon = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true, default-features = false }
crossbeam = "0.8.4"
half = "2.4.0"

[dev-dependencies]
insta = "1.34.0"
