[package]
name = "rayexec_shell"
version.workspace = true
edition.workspace = true

[dependencies]
rayexec_error = { path = '../rayexec_error' }
rayexec_execution = { path = '../rayexec_execution' }
rayexec_parser = { path = '../rayexec_parser' }
futures = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true, default-features = false, features = ["sync"] }
url = { workspace = true }
