[package]
name = "stablestore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
object_store_util = {path = "../object_store_util"}
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
async-trait = "0.1.59"
object_store = { version = "0.5.2" }
serde_json = "1.0.91"
bytes = "1.3.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3.25"
tracing = "0.1"
