[package]
name = "ext_csv"
version.workspace = true
edition.workspace = true

[dependencies]
glaredb_proto = { path = '../glaredb_proto' }
glaredb_core = { path = '../glaredb_core' }
glaredb_error = { path = '../glaredb_error' }
futures = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
url = { workspace = true }
bytes = { workspace = true }
csv-core = "0.1.12"
csv = "1.3.0"
