[package]
name = "logutil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.9"
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["std", "fmt"] }
tracing-log = "0.1.3"
