[package]
name = "glaredb_bench"
version.workspace = true
edition.workspace = true

[dependencies]
glaredb_error = { path = '../glaredb_error' }
glaredb_core = { path = '../glaredb_core' }
glaredb_rt_native = { path = '../glaredb_rt_native' }
logutil = { path = '../logutil' }
futures = { workspace = true }
clap = { version = "4.5.34", features = ["derive", "env"] }
tokio = { workspace = true }
