[package]
name = "diststore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coretypes = {path = "../coretypes"}
fmtutil = {path = "../fmtutil"}
logutil = {path = "../logutil"}
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.0"
tokio = { version = "1", features = ["full"] }
