[package]
name = "jsoncat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logutil = {path = "../logutil"}
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"
async-trait = "0.1.59"
futures = "0.3.25"
datafusion = "15.0"
arrow = { version = "*", default-features = false, features = ["serde"] }
tokio = { version = "1", features = ["full"] }
bytes = "1.3.0"
parking_lot = "0.12.1"
object_store = { version = "0.5.2" }
serde_json = "1.0.89"
