[package]
name = "datasource_mysql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datasource_common = {path = "../datasource_common"}
thiserror = "1.0"
tracing = "0.1"
async-trait = "0.1.62"
futures = "0.3.25"
tokio = { version = "1", features = ["full"] }
async-stream = "0.3.3"
datafusion = "17.0"
serde = { version = "1.0", features = ["derive"] }
mysql_async = "0.31.2"
