[package]
name = "lemur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logutil = {path = "../logutil"}
anyhow = "1.0"
thiserror = "1.0"
bitvec = { version = "1", features = ["serde"] }
paste = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.9"
async-trait = "0.1.56"
futures = "0.3.21"
rand = "0.8"
parking_lot = "0.12.1"
arrow2 = { version = "0.13", features = ["compute", "io_ipc", "io_print", "io_parquet"] }
ordered-float = { version = "3.0.0", features = ["serde"] }
fasthash = "0.4.0"

