[package]
name = "lemur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bitvec = { version = "1", features = ["serde"] }
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }

