[package]
name = "rayexec_bullet"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayexec_error = { path = "../rayexec_error" }
rayexec_proto = { path = "../rayexec_proto" }
half = { workspace = true }
num = "0.4.3"
csv-core = { version = "0.1.11", default-features = false } # Default features has libc dependency.
chrono = "0.4.39"
textwrap = { version = "0.16.1", default-features = false, features = ["unicode-width"] }
serde = { workspace = true }
flatbuffers = "24.12.23"
bytes = { workspace = true }
ahash = { workspace = true }
