[package]
name = "ext_tpch_gen"
version.workspace = true
edition.workspace = true

[dependencies]
glaredb_core = { path = '../glaredb_core' }
glaredb_error = { path = '../glaredb_error' }
tpchgen = "0.1.0"
