[package]
name = "rayexec_delta"
version.workspace = true
edition.workspace = true

[dependencies]
rayexec_proto = { path = '../rayexec_proto' }
rayexec_execution = { path = '../rayexec_execution' }
rayexec_error = { path = '../rayexec_error' }
rayexec_io = { path = '../rayexec_io' }
parquet = { path = '../parquet' }
futures = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
url = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
erased-serde = { workspace = true }

# TODO: zstd feature for parquet?
