[package]
name = "sqlrel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coretypes = {path = "../coretypes"}
sqlparser = "0.17.0"
thiserror = "1.0"
bitvec = "1"

