[package]
name = "dfutil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesutil = {path = "../bytesutil"}
datafusion = "15.0"
bytes = "1.3.0"
thiserror = "1.0"
arrow = {version = "28.0", features = ["ipc", "ffi"]}
