[package]
name = "persistence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logutil = {path = "../logutil"}
moka = { version = "0.9.4", features = ["future"] }
thiserror = "1.0"
parking_lot = "0.12.1"
tokio = { version = "1", features = ["full"] }
futures = "0.3.21"
tracing = "0.1"
async-trait = "0.1.58"
datafusion = "13.0"
object_store = { version = "0.5.1", features = ["aws", "gcp", "azure"] }
bytes = "1.2.1"
tempfile = "3"
