[package]
name = "testing"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
num_cpus = "1.16.0"
anyhow = "1.0"
walkdir = "2.3.3"
clap = { version = "4.4.13", features = ["derive"] }
glob = "0.3.1"
tracing = "0.1"
tokio = { workspace = true }
tokio-postgres = "0.7.8"
tempfile = "3"
sqllogictest = "0.19.0"
object_store = { workspace = true, features = ["gcp"] }
async-trait = { workspace = true }
regex = "1.8.1"
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
openssh = "0.10.2"
futures = { workspace = true }
ioutil = { path = "../ioutil" }
logutil = { path = "../logutil" }
glaredb = { path = "../glaredb" }
pgsrv = { path = "../pgsrv" }
sqlexec = { path = "../sqlexec" }
pgrepr = { path = "../pgrepr" }
telemetry = { path = "../telemetry" }
datafusion_ext = { path = "../datafusion_ext" }
metastore = { path = "../metastore" }
rpcsrv = { path = "../rpcsrv" }

[[test]]
harness = false
name = "sqllogictests"
path = "tests/sqllogictests/main.rs"
